### ISSUE TITLE
Fill out 'build' column

### ISSUE THREAD

**Issue by mike-rogers** [jenkinsci/rally-plugin#13]
It would be cool to fill out the 'build' column and add a link to the Jenkins build page for that job.

**Comment by mike-rogers** [comment]
This feature was released in v2.2.

**Comment by luis-echegaray** [comment]
Love the plugin by the way, was just wondering if it should fill the Builds Column under Changesets. (image below)  

It does collect the data under reports -> build dashboard but it would be great for at-a-glance traceability from one area.

![screen shot 2016-02-03 at 3 21 54 pm](https://cloud.githubusercontent.com/assets/12701030/12795851/0caab08e-ca8a-11e5-9552-47d53e9c061e.png)

**Comment by mike-rogers** [comment]
I looked into doing exactly this when I was implementing the build column functionality but as far as I could tell not even the plugin released by Rally (now CA) filled out that particular area. If you have found some documentation somewhere that describes how to fill out that area I would love to implement it!
