### ISSUE TITLE
Plugin claims "Full authentication is required to access this resource" or doesn't even push to Rally

### ISSUE THREAD

**Issue by turboscholz** [jenkinsci/rally-plugin#15]
Our Jenkins server runs behind a proxy. Connection to Rally is working, I tested it with the command  wget https://us1.rallydev.com. The index.html is saved without any error. 

I set up the Jenkins Rally plugin v2.2.0 to push the changesets and the build-status to Rally using my Rally API Key. Sometimes, not always, I get a 401 error. The following one was from this morning:

```ruby
rally update plug-in error: could not update changeset entry: java.io.IOException: HTTP/1.1 401 Full authentication is required to access this resource
com.jenkins.plugins.rally.RallyException: java.io.IOException: HTTP/1.1 401 Full authentication is required to access this resource
	at com.jenkins.plugins.rally.utils.RallyQueryBuilder.andExecuteReturningRef(RallyQueryBuilder.java:70)
	at com.jenkins.plugins.rally.connector.RallyConnector.queryForRepository(RallyConnector.java:127)
	at com.jenkins.plugins.rally.service.RallyService.updateChangeset(RallyService.java:43)
	at com.jenkins.plugins.rally.RallyPlugin.perform(RallyPlugin.java:108)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.io.IOException: HTTP/1.1 401 Full authentication is required to access this resource
	at com.rallydev.rest.client.HttpClient.executeRequest(HttpClient.java:163)
	at com.rallydev.rest.client.HttpClient.doRequest(HttpClient.java:145)
	at com.rallydev.rest.client.ApiKeyClient.doRequest(ApiKeyClient.java:37)
	at com.rallydev.rest.client.HttpClient.doGet(HttpClient.java:221)
	at com.rallydev.rest.RallyRestApi.query(RallyRestApi.java:168)
	at com.jenkins.plugins.rally.utils.RallyQueryBuilder.andExecuteReturningRef(RallyQueryBuilder.java:62)
	... 12 more
Build step 'Update Rally Task and ChangeSet' marked build as failure
```

The next build was completed without any push to rally:

```ruby
...
bd0fc1fa87e9: Image already exists
702b28a3ba42: Image already exists
latest: digest: sha256:f5d0a9b5f947bdbd0b86415d6be2b5498cd4f8d0677550dce3582765aa69551f size: 69321
+ docker rmi xxx.xyz.com:5000/myproject:latest
Untagged: xxx.xyz.com.com:5000/myproject:latest
Deleted: faea5523ca8d9a9c102c9b416bf87d807cb0606ff8041b8b679f07f6f365a697
...
Deleted: 5297f7dc3220563e4341148dfeb482c78668784e5e3f50266cbe7bb62c57b0ab
Sending e-mails to: my@mail.com
Finished: SUCCESS
```

Let me know if I should provide any further information.

**Comment by mike-rogers** [comment]
That's an interesting error. I will look into it more deeply later today.

In the meantime, when you set up your Rally API key did you check the Full Access box or the ALM WSAPI Read-only box? I think I remember some flakiness when using the latter.

**Comment by turboscholz** [comment]
Yes, the "Full Access" flag was activated when I created the key, the other flag wasn't.

**Comment by mike-rogers** [comment]
I've seen transient 401s before but there's really nothing that can be done at the plugin level. As for the build with nothing pushed to Rally, could it be that there was no associated changeset, or that the changeset had no User Story or Defect reference?

**Comment by turboscholz** [comment]
Okay, thank you for clarifying this. I still could not find the root cause for the 401 problem. Just for testing I set up a new Rally API Key today and used this for pushing the build status to Rally. It seems as if it worked, because I see the current build number with a green button in the Rally Gui for this build now.

The only thing which changed in the last time was that we moved our Jenkins to another IP address. But this should not interfere with the Rally Key I guess.

Interestingly I still can't see any output from the Rally Plugin in the Console Output in Jenkins for this build (#112):
```ruby
...
Untagged: xxx.xyz.com:5000/myproject:latest
Deleted: 11deaf0f85a53e841ee63a14ac16569a62b3b354231ce386a7a6b1f55a0ea363
Deleted: c0a5c8e965fec3b761864284f33fdebc58fbbe26c927d120978bad53d68b44f0
Deleted: 1add2553976237802a20ec7d98a30ded6d8a424d9d709338e4c2ce113c9a1552
Deleted: fb25c2196130b62ed90c55e4cf6990b5cb49ad89ab526fda2d31c94153764532
Deleted: 4d44f59f8b7b77dfac462c174f93d3c71c87279dfb59b4b3b863346e9ead1ab8
Deleted: ef0ada953484ed488c0aaedbf502a21be0ca0738785744685e96fbca22daacae
Deleted: 4666debc544c98ca280b1a4a31ac1fec34f66d2db2e11ae5e045976366e3713c
Deleted: 7f24b130f26ee18fd6d2f93571e043e3dfb0a439a3422cae555b0eb19d02f407
Deleted: 99458d084a33961d338034c6ddd2901795c15127fb58e2257e96c9c9fefc048e
Deleted: 2c699ebbc43f707506cf03c1d625ec6fe4d1b4199d890ce21cc868aa9dd248e8
Deleted: d19cefc7d57a725e329a797c8685dc01e31292c8883099a2f944bfb5839ab74b
Deleted: abfbaf78f9d4d84f677af2c3a48dc497aa808ae87a9b507fe9f3f5e963b310a6
Deleted: 1fa115d70e28792e0481f9cf0decb0803a2e71d8a44be860ef477939f0bb21c0
Deleted: 01da6b537b07b850c05af6a8f412e879b3eff918158d651bb61a63dcbca29717
Deleted: 5808fa4a5c235bf281a483941f9e1c4f24276e12750bfa6fb77f96b98bc3cd03
Deleted: 1d11b91d7fcb5724a5ad07dc90711a0b544f8ce742ae7edfa525a4faab5c39a7
Deleted: b381528cdfb86aafc2d200c5af79d711677125090d529dce1a15b1919e509ea8
Deleted: daabfa098bc1d1336f90c3f0b9921b57607f9ac4ed99fd7f845f6be10a5e5437
Deleted: 10e4e3de786d6d4b597751c0910906cee8c6ecd7fa9eb72bd64e3cf52c0d7d96
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] Copying all json files from: /var/lib/jenkins/jobs/Services/jobs/myproject/jobs/myproject/workspace/results to reports directory: /var/lib/jenkins/jobs/Services/jobs/myproject/jobs/myproject/builds/112/cucumber-html-reports
[CucumberReportPublisher] Found 1 json files.
[CucumberReportPublisher] 1. Found a json file: report.json
[CucumberReportPublisher] Generating HTML reports

Sending e-mails to: uscholz@xyz.com
Finished: SUCCESS
```

![my_app](https://cloud.githubusercontent.com/assets/5513310/11895891/6e348dc0-a582-11e5-827b-e77f93dd7e03.png)

If everything could be pushed without problem, is there really no output in the logs?

Best wishes,
Uwe

**Comment by turboscholz** [comment]
Okay, I found the problem. When we moved to another IP address, actually the whole server config was copied (I don't know how this was done by my colleges).

As a result, my Rally API key was stored incorrectly in Rally. I realized this because there are way to much dots displayed when I open the key in Jenkins. Maybe it was converted into its hash of the underlying plain text key.... -> Problem solved. The error message of the plugin was absolutely correct. :)

**Comment by mike-rogers** [comment]
Thank you for the update!

**Comment by prakashtcs** [comment]
I am configuring rally in jenkins. i couldn't see any logs related to rally in the jenkins console and the same time it has not updated anything in the rally for the user story id specified in the commit comments.

can any one please help me.
