### ISSUE TITLE
No Console Logs related to Rally

### ISSUE THREAD

**Issue by prakashtcs** [jenkinsci/rally-plugin#19]
I have configured Rally in jenkins. on running the build, i couldn't see any logs related to rally in the jenkins console and the same time nothing is been updated in rally for the user story id specified in the Github commit comments.

can anyone please help me in resolving this.

**Comment by mike-rogers** [comment]
If there are no logs indicating the plugin is running, that might mean that the publish step is never being executed. Is there another publisher upstream that is failing the build? Can you show how the plugin is configured?

**Comment by prakashtcs** [comment]
Hi Mike,

Yes, it seems none of my Post build action is executed.  I have configured one more post build action to send email notification, i didn't receive the email nor the log for sending the email.

Am i missing some configuration to enable my post build action?

**Comment by mike-rogers** [comment]
Oh, I think I know what this might be. While working on the plugin I noticed that if I triggered the build and the source code for the build hadn't changed, the most recent commit _would not_ be sent to the plugin. So what I had to do was configure the build, manually trigger, observe no publish step in the log, then create a dummy commit and retrigger the build. The existence of the new commit would trigger the publish step.

Does that sound like what you're seeing?

**Comment by prakashtcs** [comment]
Thanks Mike, now i got some log for Rally. it seems some permission issue.

com.jenkins.plugins.rally.RallyException: java.io.IOException: HTTP/1.1 401 Unauthorized
	at com.jenkins.plugins.rally.utils.RallyCreateBuilder.andExecuteReturningRefFor
